# Site settings
#title: "Vogel Street, Dunedin NZ"
#email: vogelstreet@cartoonbeats.com
description: "site by <a href='https://twitter.com/haszari'>@haszari</a>"
baseurl: ""
url: "http://vogelandbond.org"
twitter_username: vogelandbond
facebook_username: dunedinstreetart

# Build settings
markdown: kramdown
permalink: pretty
exclude: ['vendor']