# Site settings
title: "Vogel Street, Dunedin NZ"
email: vogelstreet@cartoonbeats.com
description: "Vogel Street Party & Dunedin Street Art Festival Info"
baseurl: ""
url: "http://vogelstreet.github.io"
twitter_username: vogelstreet
facebook_username: dunedinstreetart

# Build settings
markdown: kramdown
permalink: pretty
exclude: ['vendor']